traefik:
  # Deployment configuration
  deployment:
    kind: DaemonSet

  # Enable dashboard
  ingressRoute:
    dashboard:
      enabled: true

  # Ports configuration
  ports:
    web:
      port: 80
      exposedPort: 80
      nodePort: 30080
    websecure:
      port: 443
      exposedPort: 443
      nodePort: 30443
    traefik:
      port: 9000
      exposedPort: 9000

  # Service configuration
  service:
    type: NodePort

  # Enable metrics
  metrics:
    prometheus:
      enabled: true

  # Additional arguments
  additionalArguments:
    - --api.insecure=true
    - --log.level=INFO
    - --providers.kubernetescrd.allowCrossNamespace=true

  # Node selector to ensure Traefik runs on control-plane
  nodeSelector:
    ingress-ready: "true"
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
