apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-apps
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/BillyMichael/LDP.git
      revision: HEAD
      files:
      - path: "platform-apps/**/Chart.yaml"
  template:
    metadata:
      name: '{{index .path.segments 2}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/BillyMichael/LDP.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index .path.segments 1}}'