apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authelia
  namespace: auth
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`auth.local`)
      kind: Rule
      services:
        - name: authelia
          port: 80
