apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jwk-rsa
spec:
  dnsNames: [ auth.{{ .Values.global.clusterIP }}.nip.io ]
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  secretName: jwk-rsa
  usages:
    - digital signature
    - key encipherment