apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gitea
  namespace: vcs
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`gitea.local`)
      kind: Rule
      services:
        - name: gitea-http
          port: 3000
