---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lldap
  annotations:
        argocd.argoproj.io/sync-wave: '-2'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lldap-secret-store
  annotations:
        argocd.argoproj.io/sync-wave: '-2'
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lldap-secret-store
  annotations:
        argocd.argoproj.io/sync-wave: '-2'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lldap-secret-store
subjects:
  - kind: ServiceAccount
    name: lldap
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: lldap-store
  annotations:
        argocd.argoproj.io/sync-wave: '-2'
spec:
  provider:
    kubernetes:
      remoteNamespace: auth
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: lldap